company_names:
  - Korvian
  - Synvora
  - Talnix
  - Mertris
  - Orivex
  - Rynvora
  - Kaiorium
  - Valtrix
  - Torvian
  - Avolyx
  - Lumtris
  - Zenvora
  - Korixis
  - Nivdra
  - Merovia
  - Syntris
  - Elovex
  - Avotium
  - Orinix
  - Talvora
