package br.com.corely.comercial.rbac;

public enum ComercialPermission {
    COMMERCIAL_PLAN_READ,
    COMMERCIAL_PLAN_WRITE,
    COMMERCIAL_STUDENT_PLAN_READ,
    COMMERCIAL_STUDENT_PLAN_WRITE,
    COMMERCIAL_RULE_DEFINITION_READ,
    COMMERCIAL_RULE_DEFINITION_WRITE,
    COMMERCIAL_INVOICE_READ,
    COMMERCIAL_INVOICE_WRITE,
    COMMERCIAL_PAYMENT_READ,
    COMMERCIAL_PAYMENT_WRITE,
    COMMERCIAL_DASHBOARD_VIEW
}
